# Generated by Django 6.0.4 on 2026-05-30 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_milestonebadge_verifiedcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('embed_url', models.URLField()),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='game_thumbnails/')),
                ('category', models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('language', 'Language'), ('coding', 'Coding'), ('puzzle', 'Puzzle'), ('geography', 'Geography'), ('general', 'General')], default='general', max_length=20)),
                ('age_group', models.CharField(choices=[('5-8', 'Ages 5–8'), ('8-12', 'Ages 8–12'), ('12-16', 'Ages 12–16'), ('all', 'All Ages')], default='all', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('play_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-play_count'],
            },
        ),
        migrations.CreateModel(
            name='KidsDailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('HTML & CSS', 'HTML & CSS'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Geography', 'Geography'), ('Astronomy', 'Astronomy')], max_length=50)),
                ('age_group', models.CharField(choices=[('5-8', 'Explorer (5–8)'), ('8-12', 'Adventurer (8–12)'), ('12-16', 'Champion (12–16)')], max_length=10)),
                ('stars_reward', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VRContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('360_video', '360° Video'), ('webxr', 'WebXR Scene'), ('simulation', 'Simulation'), ('headset_app', 'Headset App')], max_length=20)),
                ('embed_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('webxr_scene_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='vr_thumbnails/')),
                ('subject', models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('HTML & CSS', 'HTML & CSS'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Geography', 'Geography'), ('Astronomy', 'Astronomy')], default='', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_headset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_display',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('lesson', 'Lesson'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('reminder', 'Reminder'), ('holiday', 'Holiday')], default='reminder', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(default='#FF6B6B', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.embeddedgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KidsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('avatar_choice', models.CharField(default='rocket', max_length=50)),
                ('age_group', models.CharField(choices=[('5-8', 'Explorer (5–8)'), ('8-12', 'Adventurer (8–12)'), ('12-16', 'Champion (12–16)')], default='8-12', max_length=10)),
                ('kids_mode_active', models.BooleanField(default=False)),
                ('total_stars', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('daily_goal_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kids_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KidsAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('achievement_type', models.CharField(choices=[('star', 'Star'), ('trophy', 'Trophy'), ('badge', 'Badge'), ('streak', 'Streak')], max_length=20)),
                ('icon', models.CharField(default='star', max_length=100)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('kids_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.kidsprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('headset_used', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.vrcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
